services:
  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: mqtt-broker
    ports:
      - "1883:1883"
    networks:
      - my-network

  aasx-server:
    container_name: aasx_server__
    image: docker.io/adminshellio/aasx-server-blazor-for-demo:main
    restart: unless-stopped
    ports:
      - "5001:5001"    # 실제 포트 번호로 변경
    environment:
      - Kestrel__Endpoints__Http__Url=http://*:5001
    volumes:
      - ./aasxs:/usr/share/aasxs
    command: --no-security --data-path /usr/share/aasxs --external-blazor YOURURL
    networks:
      - my-network

  mqtt-to-rest:
    build: .
    container_name: mqtt-to-rest
    depends_on:
      - mqtt-broker
      - aasx-server
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
